### PR TITLE
fix(lib): use `ipaddr.js` instead of `ip` for support IPv6

### LINKED ISSUE #2: [BUG] SSRF protection bypass
Hi Team :),
I'm a sec-researcher from HackerOne and I've discovered a good way to bypass the `SSRF protection` using `IPv6` formatted URLs ... that aren't correctly checked, allowing me to bypass the protection provided by the module and at the same time, access to the content of private and local resources ;)

I've already reported the issue on the official NPM https://hackerone.com/nodejs-ecosystem program, but the team said it's a "missed functionality and not a bug" ... so I'd like to know how can I report the issue (I add directly the report here?), and if you're ok to consider this a valid issue in order to let me know earn reputation/be awared (probably) with a CVE :).

Best, Mik

### PR DESCRIPTION
**Pull request by azu**
https://github.com/indutny/node-ip has not defined IPv4-mapped IPv6 addresses like `[::ffff:127.0.0.1]`.
Swith to use [ipaddr.js](https://github.com/whitequark/ipaddr.js) for parsing IPv6 address correctly.

[ipaddr.js](https://github.com/whitequark/ipaddr.js) has `SpecialRanges` that is defined RFC IP Address range that include IPv4-mapped IPv6 addresses.

https://github.com/whitequark/ipaddr.js/blob/3ade7dbfa1d9713f0aabe002c9a0718c4cc6cb5e/lib/ipaddr.js#L506

## Changes

- Fix to handle IPv6 address like IPv4-mapped IPv6 addresses

fix #2

### CODE REVIEW

File: src/request-filtering-agent.ts [hunk 1]
```diff
@@ -39,23 +39,34 @@ export interface RequestFilteringAgentOptions {
...
+            return;
+        }
+        if (!options.allowMetaIPAddress) {
+            // address === "0.0.0.0" || address == "::"
+            if (range === "unspecified") {
+                return new Error(`DNS lookup ${address}(family:${family}, host:${host}) is not allowed. Because, It is meta IP address.`);
+            }
+        }
+        // TODO: rename option name
+        if (!options.allowPrivateIPAddress && range !== "unicast") {
```
Comment (azu) [inline src/request-filtering-agent.ts]: I think that `allowPrivateIPAddress` option name is invalid.
`allowReservedIPAddress` is correct.

File: test/request-filtering-agent.test.ts [hunk 2]
```diff
@@ -137,11 +138,37 @@ describe("request-filtering-agent", function() {
...
+                    assert.fail(error);
+                }
+                assert.ok(/Socket is closed/i.test(error.message), `Failed at ${ipAddress}, error: ${error}`);
+            }
+        }
+    });
+    // TODO: Travis CI does not support IPv6
+    // https://docs.travis-ci.com/user/reference/overview/
+    // https://github.com/travis-ci/travis-ci/issues/8891
+    (IS_TRAVIS ? it.skip : it)("IPv6: should not request because Socket is closed", async () => {
```
Comment (azu) [inline test/request-filtering-agent.test.ts]: Travis CI does not support IPv6...

We need to other CI servier that support IPv6 network...
In locally, These tests are passed.
